### ISSUE TITLE
Running yo ko-spa error

### ISSUE THREAD

**Issue by chiyiangel** [caseyWebb/generator-ko-spa#25]
Hi , When I run the yo ko-spa to generate my application it shows this error message !

`λ  yo ko-spa
C:\Users\chiyi\AppData\Roaming\npm\node_modules\generator-ko-spa\generators\app\index.js:11
    super(...arguments)
          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as ko-spa:app] (C:\Users\chiyi\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\chiyi\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\chiyi\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:260:16)`

here is my yo & npm version
`λ yo --version
1.7.0`

`λ npm -version
3.8.6`

thank you !

**Comment by caseyWebb** [comment]
I originally made this when reworking the architecture for my work app, which I then iterated on quite a lot, leaving this terribly outdated as far as my familiarity goes.

I do plan on fixing this back up now that we've come to a stable app structure, but it may take me a few days.

**Comment by PlkMarudny** [comment]
Hi,

I tried version 1.1.0 and 1.0.0 using npm and got same error. On the other hand, the latest on npm is 1.2.0. WhIch version is supposed to be working then?

**Comment by rguedes** [comment]
Same error here. Can you help?

**Comment by larryralph** [comment]
Hi Folks

When I on a Windows 10 machine run yo ko-spa - nothing happens but this below - so with the above comments I tempted to conclude that the ko-spa generator is not working, - is that a fair conlcusion ?

C:\Users\larsp\test02>yo ko-spa

     _-----_     ╭──────────────────────────╮
    |       |    │  Hey there! Ready to get │
    |--(o)--|    │  started writing kickass │
   `---------´   │      Knockout apps?      │
    ( _´U`_ )    │         Let's go!        │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? content base: client/
? path: client/dist
? public path: /dist/
? multiple entry points? No
? name: test02
? version: 1.0.0
? description:
? keywords (space-delimited):
? author:
? license: ISC

C:\Users\larsp\test02>yo ko-spa

**Comment by caseyWebb** [comment]
Hey guys, this has long been abandoned by me. I have something similar, albeit incomplete, with [Ali](https://github.com/caseyWebb/ali). It doesn't currently have generators, but I would like to create an ali cli and include them via [plop](https://plopjs.com/).
